[package]
name = "smorust"
description = "Solve SVM training problem using SMO"
version = "0.1.0"
authors = ["Nico Strasdat <nstrasdat@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wotzlaff/smorust"
keywords = ["smo", "svm", "machine-learning"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "smorust"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.0"