[package]
name = "rusvm"
description = "Solve SVM training problems"
version = "0.2.0"
authors = ["Nico Strasdat <nstrasdat@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wotzlaff/rusvm"
keywords = ["smo", "svm", "machine-learning"]

[dependencies]
ndarray = "0.15"
ndarray-linalg = { version = "0.16", features = ["intel-mkl-static"], optional = true }
caches = "0.2.6"

[features]
default = ["newton", "time"]
newton = ["dep:ndarray-linalg"]
time = []