[package]
name = "smorust"
description = "Solve SVM training problem using SMO"
version = "0.1.4"
authors = ["Nico Strasdat <nstrasdat@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wotzlaff/smorust"
keywords = ["smo", "svm", "machine-learning"]

[dependencies]
ndarray = "0.15.0"
caches = "0.2.6"