[package]
name = "rusvm"
description = "Solve SVM training problems"
version = "0.1.6"
authors = ["Nico Strasdat <nstrasdat@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/wotzlaff/rusvm"
keywords = ["smo", "svm", "machine-learning"]

[dependencies]
ndarray = "0.15.0"
ndarray-linalg = { version = "0.16", features = ["intel-mkl-static"] }
caches = "0.2.6"